import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { ClipboardList, AlertCircle, Clock, CheckCircle2 } from 'lucide-react';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import api from '../../services/api';

import { useAuth } from '../../context/AuthContext';
import toast from 'react-hot-toast';

const COLORS = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6'];

const AdminDashboard = () => {
  const { user } = useAuth();
  const [isAddStudentOpen, setIsAddStudentOpen] = React.useState(false);
  const [studentForm, setStudentForm] = React.useState({ name: '', admissionNumber: '', dob: '', studentClass: '', section: '', rollNumber: '' });
  const [isSubmitting, setIsSubmitting] = React.useState(false);
  
  const { data, isLoading, error } = useQuery({
    queryKey: ['admin-analytics'],
    queryFn: async () => {
      const response = await api.get('/analytics/dashboard');
      return response.data.data;
    }
  });

  const handleAddStudent = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      await api.post('/students', studentForm);
      toast.success('Student added successfully. Parents can now join using this Admission Number.');
      setIsAddStudentOpen(false);
      setStudentForm({ name: '', admissionNumber: '', dob: '', studentClass: '', section: '', rollNumber: '' });
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to add student');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isLoading) return <div className="animate-pulse">Loading admin dashboard...</div>;
  if (error) return <div className="text-red-500">Failed to load dashboard data.</div>;

  const stats = [
    { name: 'Total Issues', stat: data.overview.totalIssues, icon: ClipboardList, color: 'bg-primary-600' },
    { name: 'Critical Issues', stat: data.overview.critical, icon: AlertCircle, color: 'bg-red-500' },
    { name: 'Pending Assignment', stat: data.overview.pending, icon: Clock, color: 'bg-amber-500' },
    { name: 'Resolved', stat: data.overview.resolved, icon: CheckCircle2, color: 'bg-emerald-500' },
  ];

  const school = user?.schoolId as any; // Populated school object from getProfile

  const handleDownloadPDF = () => {
    if (!school) return;
    const html = `<html><body style="font-family: sans-serif; text-align: center; padding: 50px;">
        <h1>Welcome to ${school.schoolName}</h1>
        <div style="margin: 40px 0; padding: 20px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;">
            <p style="text-transform: uppercase; color: #64748b; font-size: 12px; letter-spacing: 1px;">Your School Code</p>
            <h2 style="font-size: 32px; font-family: monospace; margin: 10px 0;">${school.schoolCode}</h2>
        </div>
        <p>Please share this code with your teachers and parents to join the portal.</p>
        <p style="margin-top: 50px; color: #94a3b8; font-size: 12px;">Generated by School Guardian</p>
    </body></html>`;
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 250);
    }
  };

  return (
    <div>
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-slate-900">Admin Dashboard</h1>
        <p className="text-sm text-slate-500 mt-1">System-wide overview of all facility conditions and repairs.</p>
      </div>

      {school && school.schoolCode && (
        <div className="mb-8 bg-gradient-to-r from-primary-600 to-primary-800 rounded-lg shadow-lg text-white p-6 relative overflow-hidden">
          <div className="relative z-10 flex flex-col md:flex-row items-center justify-between">
            <div className="mb-4 md:mb-0">
              <h2 className="text-2xl font-bold mb-1">Welcome to {school.schoolName}</h2>
              <p className="text-primary-100">Get your teachers and parents onboarded instantly.</p>
            </div>
            <div className="flex flex-col sm:flex-row items-center space-y-3 sm:space-y-0 sm:space-x-4 bg-white/10 p-4 rounded-lg backdrop-blur-sm border border-white/20">
              <div className="text-center sm:text-left">
                <span className="text-xs text-primary-200 uppercase tracking-wider block mb-1">Your School Code</span>
                <span className="text-2xl font-mono font-bold tracking-wider">{school.schoolCode}</span>
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(school.schoolCode);
                    toast.success('School code copied!');
                  }}
                  className="bg-white text-primary-700 px-4 py-2 rounded font-medium hover:bg-primary-50 transition-colors shadow-sm"
                >
                  Copy
                </button>
                <button 
                  onClick={() => setIsAddStudentOpen(true)}
                  className="bg-primary-500 text-white border border-primary-400 px-4 py-2 rounded font-medium hover:bg-primary-400 transition-colors shadow-sm"
                >
                  Add Student
                </button>
                <button 
                  onClick={handleDownloadPDF}
                  className="bg-slate-800 text-white border border-slate-700 px-4 py-2 rounded font-medium hover:bg-slate-900 transition-colors shadow-sm"
                >
                  Welcome PDF
                </button>
              </div>
            </div>
          </div>
          {/* Decorative shapes */}
          <div className="absolute -top-24 -right-24 w-64 h-64 bg-white opacity-5 rounded-full blur-3xl"></div>
          <div className="absolute -bottom-24 -left-24 w-64 h-64 bg-white opacity-5 rounded-full blur-3xl"></div>
        </div>
      )}

      <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((item) => (
          <div key={item.name} className="relative bg-white pt-5 px-4 pb-12 sm:pt-6 sm:px-6 shadow rounded-lg overflow-hidden border border-slate-100">
            <dt>
              <div className={`absolute rounded-md p-3 ${item.color}`}>
                <item.icon className="h-6 w-6 text-white" aria-hidden="true" />
              </div>
              <p className="ml-16 text-sm font-medium text-slate-500 truncate">{item.name}</p>
            </dt>
            <dd className="ml-16 pb-6 flex items-baseline sm:pb-7">
              <p className="text-2xl font-semibold text-slate-900">{item.stat}</p>
            </dd>
          </div>
        ))}
      </div>

      {/* Charts Section */}
      <div className="mt-8 grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white shadow rounded-lg border border-slate-100 p-6">
          <h2 className="text-lg font-medium text-slate-900 mb-4">Issues by Category</h2>
          <div className="h-64 flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={data.overview.byCategory || []}
                  cx="50%"
                  cy="50%"
                  labelLine={false}
                  outerRadius={80}
                  fill="#8884d8"
                  dataKey="count"
                  nameKey="_id"
                  label={(props: any) => `${props._id} ${(props.percent * 100).toFixed(0)}%`}
                >
                  {(data.overview.byCategory || []).map((_entry: any, index: number) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
        
        <div className="bg-white shadow rounded-lg border border-slate-100 p-6">
          <h2 className="text-lg font-medium text-slate-900 mb-4">Issues by Status</h2>
          <div className="h-64 flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={data.overview.byStatus || []} margin={{ top: 20, right: 30, left: 0, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0" />
                <XAxis dataKey="_id" axisLine={false} tickLine={false} tick={{fill: '#64748B'}} />
                <YAxis axisLine={false} tickLine={false} tick={{fill: '#64748B'}} />
                <Tooltip cursor={{fill: '#F8FAFC'}} contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}} />
                <Bar dataKey="count" fill="#3B82F6" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
      
      {/* Recent Activity */}
      <div className="mt-8 bg-white shadow rounded-lg border border-slate-100 p-6">
        <h2 className="text-lg font-medium text-slate-900 mb-4">System Activity Log</h2>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-slate-200">
            <thead>
              <tr>
                <th className="px-6 py-3 bg-slate-50 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Action</th>
                <th className="px-6 py-3 bg-slate-50 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Module</th>
                <th className="px-6 py-3 bg-slate-50 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Date</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-slate-200">
              {data.recentActivities?.map((activity: any) => (
                <tr key={activity._id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-900">{activity.action}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">{activity.module}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">
                    {new Date(activity.createdAt).toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {isAddStudentOpen && (
        <div className="fixed inset-0 bg-slate-900/50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
            <h3 className="text-xl font-bold text-slate-900 mb-4">Add New Student</h3>
            <p className="text-sm text-slate-600 mb-6">Create a student record so parents can register and claim it.</p>
            
            <form onSubmit={handleAddStudent} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700">Full Name</label>
                <input
                  type="text"
                  required
                  value={studentForm.name}
                  onChange={e => setStudentForm({ ...studentForm, name: e.target.value })}
                  className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-slate-700">Admission Number</label>
                <input
                  type="text"
                  required
                  value={studentForm.admissionNumber}
                  onChange={e => setStudentForm({ ...studentForm, admissionNumber: e.target.value })}
                  className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-slate-700">Date of Birth (Optional)</label>
                <input
                  type="date"
                  value={studentForm.dob}
                  onChange={e => setStudentForm({ ...studentForm, dob: e.target.value })}
                  className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
              </div>

              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700">Class</label>
                  <input
                    type="text"
                    value={studentForm.studentClass}
                    onChange={e => setStudentForm({ ...studentForm, studentClass: e.target.value })}
                    className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700">Section</label>
                  <input
                    type="text"
                    value={studentForm.section}
                    onChange={e => setStudentForm({ ...studentForm, section: e.target.value })}
                    className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700">Roll No</label>
                  <input
                    type="text"
                    value={studentForm.rollNumber}
                    onChange={e => setStudentForm({ ...studentForm, rollNumber: e.target.value })}
                    className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                  />
                </div>
              </div>
              
              <div className="pt-4 flex space-x-3 justify-end">
                <button
                  type="button"
                  onClick={() => setIsAddStudentOpen(false)}
                  className="bg-white border border-slate-300 rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="bg-primary-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50"
                >
                  {isSubmitting ? 'Adding...' : 'Add Student'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminDashboard;
