import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useNavigate, Link } from 'react-router-dom';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import toast from 'react-hot-toast';
import { Building2, KeyRound } from 'lucide-react';

const registerSchoolSchema = z.object({
  schoolName: z.string().min(3, 'School name must be at least 3 characters'),
  address: z.string().min(5, 'Please provide a complete address'),
  principalName: z.string().min(2, 'Principal name is required'),
  contactEmail: z.string().email('Please provide a valid school email'),
  contactPhone: z.string().min(10, 'Please provide a valid phone number'),
  adminEmail: z.string().email('Please provide a valid admin email for login'),
  adminPassword: z.string().min(6, 'Password must be at least 6 characters'),
});

const RegisterSchool = () => {
  const navigate = useNavigate();
  const { login } = useAuth();
  const [loading, setLoading] = useState(false);
  const [successData, setSuccessData] = useState<{ schoolCode: string; schoolName: string } | null>(null);

  const { register, handleSubmit, formState: { errors } } = useForm({
    resolver: zodResolver(registerSchoolSchema),
  });

  const handleDownloadPDF = () => {
    if (!successData) return;
    const html = `<html><body style="font-family: sans-serif; text-align: center; padding: 50px;">
        <h1>Welcome to ${successData.schoolName}</h1>
        <div style="margin: 40px 0; padding: 20px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;">
            <p style="text-transform: uppercase; color: #64748b; font-size: 12px; letter-spacing: 1px;">Your School Code</p>
            <h2 style="font-size: 32px; font-family: monospace; margin: 10px 0;">${successData.schoolCode}</h2>
        </div>
        <p>Please share this code with your teachers and parents to join the portal.</p>
        <p style="margin-top: 50px; color: #94a3b8; font-size: 12px;">Generated by School Guardian</p>
    </body></html>`;
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 250);
    }
  };

  const onSubmit = async (data: any) => {
    setLoading(true);
    try {
      const response = await api.post('/schools/register', data);
      toast.success('School registered successfully!');
      
      const { school, user } = response.data.data;
      
      // Store token and populate auth context
      if (response.data.data.token) {
        localStorage.setItem('token', response.data.data.token);
      }
      
      // We explicitly call login to set the context state
      await login(data.adminEmail, data.adminPassword);

      setSuccessData({
        schoolCode: school.schoolCode,
        schoolName: school.schoolName
      });
      
    } catch (error: any) {
      toast.error(error.response?.data?.message || 'Failed to register school');
      setLoading(false);
    }
  };

  if (successData) {
    return (
      <div className="text-center py-12 px-4 sm:px-6 lg:px-8">
        <div className="mx-auto flex items-center justify-center h-16 w-16 rounded-full bg-emerald-100 mb-6">
          <Building2 className="h-8 w-8 text-emerald-600" />
        </div>
        <h2 className="text-3xl font-extrabold text-slate-900 mb-2">Welcome aboard!</h2>
        <p className="text-lg text-slate-600 mb-8">
          {successData.schoolName} has been successfully registered.
        </p>
        
        <div className="bg-white rounded-lg shadow-sm border border-slate-200 p-8 max-w-md mx-auto mb-8 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-primary-500 to-emerald-500"></div>
          <h3 className="text-sm font-medium text-slate-500 uppercase tracking-wide mb-4 mt-2">Your School Code</h3>
          <div className="flex items-center justify-center space-x-3 bg-slate-50 py-4 px-6 rounded-md border border-slate-200">
            <KeyRound className="h-6 w-6 text-primary-500" />
            <span className="text-3xl font-mono font-bold text-slate-900 tracking-wider">{successData.schoolCode}</span>
          </div>
          <p className="mt-4 text-sm text-slate-500 mb-6">
            Share this code with your teachers and parents so they can join your school.
          </p>
          <div className="flex flex-col space-y-3">
            <button
              onClick={() => {
                navigator.clipboard.writeText(successData.schoolCode);
                toast.success('Code copied to clipboard');
              }}
              className="w-full inline-flex justify-center py-2 px-4 border border-slate-300 rounded-md shadow-sm text-sm font-medium text-slate-700 bg-white hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 transition-colors"
            >
              Copy School Code
            </button>
            <button
              onClick={handleDownloadPDF}
              className="w-full inline-flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-slate-800 hover:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-900 transition-colors"
            >
              Download Welcome PDF
            </button>
          </div>
        </div>

        <Link
          to="/dashboard"
          className="inline-flex justify-center py-3 px-8 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-primary-600 hover:bg-primary-700 transition-colors"
        >
          Go to Admin Dashboard
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto">
      <div className="text-center mb-8">
        <h2 className="text-3xl font-extrabold text-slate-900">Register Your School</h2>
        <p className="mt-2 text-sm text-slate-600">
          Set up your school's workspace and get your unique School Code.
        </p>
      </div>

      <div className="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
        <form className="space-y-6" onSubmit={handleSubmit(onSubmit)}>
          <div className="grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8">
            
            <div className="sm:col-span-2">
              <label className="block text-sm font-medium text-slate-700">School Name</label>
              <div className="mt-1">
                <input
                  {...register('schoolName')}
                  type="text"
                  className="appearance-none block w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
                {errors.schoolName && <p className="mt-1 text-sm text-red-600">{errors.schoolName.message as string}</p>}
              </div>
            </div>

            <div className="sm:col-span-2">
              <label className="block text-sm font-medium text-slate-700">Complete Address</label>
              <div className="mt-1">
                <input
                  {...register('address')}
                  type="text"
                  className="appearance-none block w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
                {errors.address && <p className="mt-1 text-sm text-red-600">{errors.address.message as string}</p>}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700">School Contact Email</label>
              <div className="mt-1">
                <input
                  {...register('contactEmail')}
                  type="email"
                  className="appearance-none block w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
                {errors.contactEmail && <p className="mt-1 text-sm text-red-600">{errors.contactEmail.message as string}</p>}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700">School Contact Phone</label>
              <div className="mt-1">
                <input
                  {...register('contactPhone')}
                  type="text"
                  className="appearance-none block w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
                {errors.contactPhone && <p className="mt-1 text-sm text-red-600">{errors.contactPhone.message as string}</p>}
              </div>
            </div>

            <div className="sm:col-span-2 pt-4 border-t border-slate-200">
              <h3 className="text-lg font-medium text-slate-900 mb-4">Admin Account Details</h3>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700">Principal/Admin Name</label>
              <div className="mt-1">
                <input
                  {...register('principalName')}
                  type="text"
                  className="appearance-none block w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
                {errors.principalName && <p className="mt-1 text-sm text-red-600">{errors.principalName.message as string}</p>}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700">Admin Login Email</label>
              <div className="mt-1">
                <input
                  {...register('adminEmail')}
                  type="email"
                  className="appearance-none block w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
                {errors.adminEmail && <p className="mt-1 text-sm text-red-600">{errors.adminEmail.message as string}</p>}
              </div>
            </div>

            <div className="sm:col-span-2">
              <label className="block text-sm font-medium text-slate-700">Admin Password</label>
              <div className="mt-1">
                <input
                  {...register('adminPassword')}
                  type="password"
                  className="appearance-none block w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                />
                {errors.adminPassword && <p className="mt-1 text-sm text-red-600">{errors.adminPassword.message as string}</p>}
              </div>
            </div>

          </div>

          <div className="pt-4">
            <button
              type="submit"
              disabled={loading}
              className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 transition-colors"
            >
              {loading ? 'Creating Workspace...' : 'Register School'}
            </button>
          </div>

          <div className="mt-6 text-center text-sm">
            <span className="text-slate-600">Already registered? </span>
            <Link to="/login" className="font-medium text-primary-600 hover:text-primary-500">
              Go to Login
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
};

export default RegisterSchool;
